### ISSUE TITLE
A Shiny for table?

### ISSUE THREAD

**Issue by ShixiangWang** [coolbutuseless/emphatic#1]
This is really a cool package and I found it also works for html in https://coolbutuseless.github.io/package/emphatic/articles/intro.html. Is it possible to provide a Shiny for table rendering like https://github.com/renkun-ken/formattable? 

Best,

Shixiang

**Comment by coolbutuseless** [comment]
Could you give me an example of what you want to achieve so I can better understand the issue? thanks.
