### ISSUE TITLE
Typst backend

### ISSUE THREAD

**Issue by coolbutuseless** [coolbutuseless/emphatic#12]
- [x] Output to typst code **Now using `raw` blocks**
- [x] Detect when rendering to typst from quarto, and call 'as_typst()' on the emphatic object
- [x] Can I do anything about stopping text reflow or setting overflow to hidden for wide tables? **Nope**
- [x] What characters need to be escaped? None. Escaping not needed in `raw` mode.
- [x] Fix legends when using typst
- [x] Something funky going on with line-ending backslash

**Comment by cscheid** [comment]
I've looked into the output generated by `emphatic` and I hope that Quarto can emit typst output correctly almost without changes.

We are still designing the feature, and so we have some flexibility to do whatever is best for you. With that said, I think it would be less bug-prone for us to assume that `emphatic` would be willing to emit (for example) a wrapper div with class `quarto-use-in-typst-output`.

**Comment by coolbutuseless** [comment]
I assume `emphatic` will have to produce typst-style markup to support coloured text in typst

E.g. 
* in latex every colour character sequence is `\colorbox[]{\textcolor[]{hello}}`
* in html it's `<span style="background-color: ..."><span style="color: ..">Hello</span><span>`

So for typst I was envisaging something like this (excuse the code, this is what 5 minutes googling got me):

```
#highlight(fill: rgb("aaaaaa"))[#text(font: "New Computer Modern Mono", fill: rgb("#0000ff"))[Hello]]
```

@cscheid I know nothing of typst syntax or how quarto does this rendering (via pandoc I assume).  So if you have an idea on a good approach, then I'm all ears!

**Comment by coolbutuseless** [comment]
This is how I think the generated output will work.

* `#highlight` for background fill behind text
* `#text` for font colour
* Using `\u{00a0}` for non-breaking space which is displayed and filled 
* And the only thing I've found to output raw typst code to get rendered is `knitr::raw_block(txt, type = 'typst')`.  There's probably a better way!

But I think @cscheid that you're advocating that I could output something simpler and let `quarto` do the conversion to `typst` format?

```{r}
'''{r}
txt <- r"(
#highlight(fill: rgb("aaaaaa"))[
  #text(font: "Courier New", fill: rgb("#0000ff"))[
    Hello\u{00a0}\u{00a0}\u{00a0}\u{00a0}there \
  ] 
]
#highlight(fill: rgb("556688"))[
  #text(font: "Courier New", fill: rgb("#00ffff"))[
    Second\u{00a0}
  ]   
]
#highlight(fill: rgb("88aabb"))[
  #text(font: "Courier New", fill: rgb("#ffaa88"))[
    \u{00a0}Line
  ] 
]
)"

knitr::raw_block(txt, type = 'typst')
'''
```

**Comment by coolbutuseless** [comment]
I've merged in some changes on main to add `typst` support.

It mostly works.  Major issue is that if the table overflows the page, typst tries to reflow text - which is not what you really want for this.

I can't figure out how to disable the reflow (or set overflow text to be hidden).  

There is a 'font_size" argument in `as_typst()` so the table can be shrunk.


@cscheid I'm more than happy to consider any other approach you might be thinking about!

**Comment by cscheid** [comment]
> But I think @cscheid that you're advocating that I could output something simpler and let quarto do the conversion to typst format?

That's right. You're faster than I am :) We're hoping to be able to literally read your HTML in Quarto, and emit Typst in response, which would have required (almost) no effort on your part. That's the approach we're taking with tables.

But if you have written the Typst code and it works, then it works 🎉 

EDIT: See a prototype PR by @gordonwoodhull here https://github.com/quarto-dev/quarto-cli/pull/9545

**Comment by coolbutuseless** [comment]
the html-to-typst approach looks promising!   

The advantage emphatic has here is that all the raw text and colours are stored separately and much easier to assemble directly to typst, rather than going via html

**Comment by coolbutuseless** [comment]
Current 'typst' support is good enough for now. Open an issue if it fails, or there's something amiss.
