### ISSUE TITLE
Emphatic with View

### ISSUE THREAD

**Issue by llrs** [coolbutuseless/emphatic#14]
Cool package! I think I'll use a lot the `hl_grep` function :smile: . 

When checking some long tables with this kind of simple highlighting would be very helpful to just go through the table to find some interesting rows (although it could be done with first subsetting and printing it on the terminal if you knew what one is looking for).
I was testing `hl` and I found that it doesn't work well with `View` (both in Rstudio and raw R): colors are not present in the new window.
I don't know if there is a way to make it compatible with it or not (I tried with `as_html` but that is not compatible with View as it creates a long html string).

**Comment by coolbutuseless** [comment]
The rendering of colours is quite custom/manual.

I don't think there's any way to pass this colour information to "View()" and have it render it appropriately.

Do you know of any examples of the output from "View" being customised?

**Comment by llrs** [comment]
Now that I think of it no. 
I think that Rstudio provides its own View to work with the IDE and I thought it could be used. But `gt` and similar packages just render the tables in the viewer panel, so I an not sure if it is possible or not.

**Comment by coolbutuseless** [comment]
Closing as "not possible".
