### ISSUE TITLE
Emphatic environment confusion

### ISSUE THREAD

**Issue by jmw86069** [coolbutuseless/emphatic#15]
I really love the idea of this package! I'm trying to wrap it into a little helper function so I can preview a `data.frame` using some logic I put together.

I have a frustratingly simple question. I encountered an error in how the `cols` values are evaluated when calling `hl()` from inside a function. And I can't figure out what combination of `quo()`, `ensym()`, `quote()`, `expression()`, `!!`, `{{` might solve it for me.

I want to pass a character string as a variable to `hl()` and it is giving an error - but only when I call `hl()` from inside a function.

Here is a reproducible example:
```R
df <- data.frame(A=1:5, B=6:10)

df |> emphatic::hl(cols="B", palette=scale_color_viridis_c())
```
Works fine:
<img width="59" alt="image" src="https://github.com/user-attachments/assets/38325f8d-f7a9-496f-842d-be52d588bffb">

Passing a variable also works, as expected:
```R
this_column <- "B"
df |> emphatic::hl(cols=this_column, palette=scale_color_viridis_c())
```
Voila.
<img width="59" alt="image" src="https://github.com/user-attachments/assets/c8a0b511-e533-431a-b8e6-289f9075768b">

Calling the same thing from inside a function:
```R
wrap_it <- function(df, use_this_column="A"){
   df <- df |> emphatic::hl(cols=use_this_column,
      palette=ggplot2::scale_color_viridis_c())
}
wrap_it(df)
```
Does not work, here is the error:
`Error in eval(expr, envir = env) : object 'use_this_column' not found`

I can only get it to work if the variable `use_this_column` is defined in `globalenv()` or `parent.env()` but not inside the function itself. I do not understand environments well enough to know why the variable in the function is not accessible to your `eval()` function on line 146 of `utils-index-lookup.R`.

If I assign `<<-` (which I do not want to do, but it is evidence of something, haha) then it works:
```R
rm(use_this_column)
wrap_it <- function(df, use_this_column="A"){
   use_this_column <<- use_this_column;
   df <- df |> emphatic::hl(cols=use_this_column,
      palette=ggplot2::scale_color_viridis_c())
}
(wrap_it(df))
```
<img width="63" alt="image" src="https://github.com/user-attachments/assets/1893f87c-fe23-43d9-a2a0-64f1e78e6ec5">

Hopefully this is a dumb simple question, I would greatly appreciate if you could save me from myself. :)

**Comment by coolbutuseless** [comment]
Thanks for raising the issue.   This error has to do with how I'm passing around environments in order to do variable selection similar to tidyverse-select.
 
I've made a few changes in a new branch called  `calling-env`.  Could you try it and see if it fixes your issue?

i.e.  `remotes::install_github('coolbutuseless/emphatic', ref = 'calling-env')`

**Comment by jmw86069** [comment]
Niiiice! It worked! My issue is resolved, thank you so much!

**Comment by coolbutuseless** [comment]
Great!  If you run into similar issues please let me know.    My use case for emphatic is definitely interactive-at-the-console, so your use within functions could throw up more interesting cases.
