### ISSUE TITLE
Color Legend needed to determine Higher or Lower values in a DF column

### ISSUE THREAD

**Issue by sfd99** [coolbutuseless/emphatic#2]
**Hi Mike,** 

**emphatic** is _truly_   a great pkg.
Easy and useful!.

An important suggestion (IMHO):

mtcars %>%
   hl(ggplot2::scale_colour_viridis_c(), rows = cyl %in% c(6, 8), cols = mpg)

shows different color for the "mpg" col. 
OK!

But, for the "mpg" col...
 -  which colors correspond to the higher / highest "mpg" values?
 -  which colors correspond to the lower  / lowest "mpg" values?.

It becomes hard to viz many colors 
with their _corresponding_ value range....

Fun Suggestion:
 Add a Color <==> Value Legend,
 next to the DF!. 
Legend will serve as a visual color / value reference.

**SFd99**
**SF**

**Comment by coolbutuseless** [comment]
Thanks for the suggestion!

Added a legend in release v0.1.3 https://github.com/coolbutuseless/emphatic/commit/23eb363f00f55436b21e50a43ed05074049bb3e4
