### ISSUE TITLE
[FR]: margin argument in hl_mat()

### ISSUE THREAD

**Issue by Eluvias** [coolbutuseless/emphatic#6]
Will a margin argument make sense in `hl_mat()` to determine how the colour vector is alternating, i.e., `.margin = 1` by row and
`.margin = 2` by colum (default)?

See the issue in  case B  for a matrix object.

``` r
library(emphatic)

x1 <- head(mtcars, 4)
x2 <- head(mtcars, 3)

# CASE A
hl(x1, colour = c("blue", "yellow"))
hl_mat(as.matrix(x1), colour = c("blue", "yellow"))
```

``` r

# CASE B
hl(x2, colour = c("blue", "yellow"))
hl_mat(as.matrix(x2), colour = c("blue", "yellow"))
#> Warning in mat[mat_ids] <- final_colour: number of items to replace is not a
#> multiple of replacement length
```
## SCREENSHOT
![εικόνα](https://user-images.githubusercontent.com/22600883/103176895-2cd27000-487e-11eb-86f9-673cf0203fdd.png)

**Comment by coolbutuseless** [comment]
Good news/bad news:

Good news: `hl_mat()` now has a `byrow` argument that I think works how you would like.

Bad news: I'm not exporting `hl_mat()` for the initial release as I've reached a bit of a roadblock trying to describe its interface and things got messy.    It's still in the code, but you'll have to use `emphatic:::hl_mat()` to access.
